<a href="https://colab.research.google.com/github/jiin124/2021_2_SAI_ML/blob/main/Numpy%EA%B8%B0%EB%B3%B8_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## ndarray를 편리하게 생성하기 - arange,zeros,ones

In [2]:
import numpy as np

In [ ]:
sequence_array=np.arange(10)
sequence_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
sequence_array.dtype


dtype('int64')

In [ ]:
sequence_array.shape

(10,)

In [ ]:
#zeros()는 함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 0으로 채운 해당 shape을 가진 ndarry를 반환한다.
zero_array=np.zeros((3,2),dtype='int32')
zero_array

array([[0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [ ]:
one_array=np.ones((3,2))
one_array

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

### ndarray의 차원과 크기를 변경하는 reshape()

In [ ]:
array1=np.arange(10)
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
array2=array1.reshape(2,5)
array2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
#-1을 reshape의 인자로 적용했을 때 어떻게 될까
array2=array1.reshape(-1,5)
array2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
array3=array1.reshape(5,-1)
array3

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

고정된 나머지 값에 맞는 로우를 자동으로 새롭게 생성해 변환하라는 소리!! 즉 10개의 숫자가 있는데 reshape(5,-1)일때 5*2 로 5행 2열로 변환하라는 소리이다

In [ ]:
array1=np.arange(8)
array1.reshape(-1,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

### 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱

넘파이에서 ndarray 내의 일부 데이터 세트나 특정 데이터만을 선택할 수 있도록 하는 인덱싱에 대해 알아보겠다.
1. 특정한 데이터만 추출 : 원하는 위치의 인덱스 값을 지정하면 해당 위치의 데이터가 반환된다.
2.  슬라이싱 : 슬라이싱은 연속된 인덱스 상의 ndarray를 추출하는 방식이다. 
3. 팬시 인덱싱 : 일정한 인덱싱 집합을 리스트 또는 ndarray 형태로 지정해 해당 위치에 있는 데이터의 ndarray를 반환한다. 
4. 불린 인덱싱 : 특정조건에 해당하는지 여부인 true/false 값 이덱싱 집합을 기반으로 True에 해당하는 인덱스 위치에 있는 데이터의 ndarray를 반환한다. 

### 단일 값 추출

In [ ]:
#1부터 9까지의 1차원 ndarray 생성
array1=np.arange(start=1,stop=10)
array1[3]

4

In [ ]:
array1=np.arange(1,10)
array2=array1.reshape(3,3)
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
array2[0,0]


1

In [ ]:
array2[0,1]

2

In [ ]:
array2[1,0]

4

In [ ]:
array1=np.arange(1,10)
array2=array1.reshape(3,3)
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
array2[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [ ]:
array2[1:3,0:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [ ]:
array2[1:3,:]

array([[4, 5, 6],
       [7, 8, 9]])

In [ ]:
array2[:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
array2[:2,1:]

array([[2, 3],
       [5, 6]])

In [ ]:
array2[:2,0]

array([1, 4])

## 팬시 인덱싱

팬시 인덱싱은 리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray를 반환하는 인덱싱 방식이다. 

In [4]:
array1=np.arange(1,10)
array2=array1.reshape(3,3)
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
array3=array2[[0,1],2]
array3

array([3, 6])

0,1행에 있는 2번째 숫자를 가져오라는 뜻

In [7]:
array4=array2[[0,1],0:2]
array4

array([[1, 2],
       [4, 5]])

## 불린 인덱싱

불린 인덱싱은 조건 필터링과 검색을 동시에 할 수 있기 때문에 매우 자주 사용되는 인덱싱 방식이다. 

In [8]:
array=np.arange(1,10)
array[array>5]

array([6, 7, 8, 9])

In [9]:
#그냥 조건식 할당시
array>5

array([False, False, False, False, False,  True,  True,  True,  True])

해당하는 값들은 True로 처리된다.

## 행렬의 정렬 - sort()와 argsort()

넘파이에서 행렬을 정렬하는 대표적인 방법인 np.sort()과 ndarray.sort()그리고 정렬된 행렬의 인덱스를 반환하는 argsort()

### 행렬 정렬

In [10]:
org_array=np.array([3,2,1,4])
org_array

array([3, 2, 1, 4])

In [12]:
sort_array=np.sort(org_array)
sort_array

array([1, 2, 3, 4])

In [13]:
sort_array2=org_array.sort()


In [16]:
print(sort_array2)

None


In [17]:
org_array

array([1, 2, 3, 4])

np.sort()는 원본 행렬을 변경하지 않고 정렬된 형태로 반환했고, ndarray.sort()는 원본 행렬을 정렬한 값으로 변환했다. 둘다 기본적으로 오름차순으로 행렬 내 원소를 정렬했으나 내림차순으로 정렬하기 위해서는 [::-1]을 적용한다. 

In [18]:
sort_array1=np.sort(org_array)[::-1]

In [19]:
sort_array1

array([4, 3, 2, 1])

행렬이 2차원 이상일 경우 axis 축 값 설정을 통해 로우 방향, 또는 칼럼 방향으로 정렬을 수행 할 수 있다. 

In [20]:
array1=np.array([[8,12],
                 [7,1]])

sort_array1=np.sort(array1,axis=0)#로우 방향으로 정렬

In [21]:
sort_array1

array([[ 7,  1],
       [ 8, 12]])

In [22]:
sort_array2=np.sort(array1,axis=1)#컬럼 방향으로 정렬
sort_array2

array([[ 8, 12],
       [ 1,  7]])

## 정렬된 행렬의 인덱스를 반환

원본 행렬이 정렬되었을 때 기존 원본 행렬의 원소에 대한 인덱스를 필요로 할때 np.argsort()를 이용한다. np.argsort()는 정렬 행렬의 원본 행렬 인덱스를 ndarray형으로 반환한다. 
내림차순으로 정렬시 원본 행렬의 인덱스를 구하는 것도 np.argsort()[::-1] 와 같이 [::-1]을 적용하면 된다

In [23]:
org_array=np.array([3,1,9,5])
sort_indices=np.argsort(org_array)
print(sort_indices)

[1 0 3 2]


## 선형대수 연산 -  행렬내적과 전치 행렬 구하기

### 행렬 내적(행렬 곱)

In [24]:
A=np.array([[1,2,3],
            [4,5,6]])
B=np.array([[7,8],
            [9,10],
            [11,12]])
dot_product=np.dot(A,B)
print(dot_product)

[[ 58  64]
 [139 154]]


### 전치 행렬

원 행렬에서 행과 열 위치를 교환한 원소로 구성한 행렬을 그 행렬의 전치 행렬이라고 한다. 

In [25]:
A=np.array([[1,2],
            [3,4]])
transpose_mat=np.transpose(A)
print(transpose_mat)

[[1 3]
 [2 4]]
